"""Offline Bilibili boundaries: recorded-event normalization and lifecycle.

This package adapts a documented, recorded Bilibili input envelope into the
canonical Danmaku message model and owns the credential-free, transport-
independent connection lifecycle state machine. It is deterministic and
offline-only: it validates a frozen fixture contract, maps supported danmaku,
gift, guard, and super-chat events into ``source="bilibili"`` messages, and
decides connection state, failure classification, and bounded reconnect
scheduling. There is no network access, credential handling, or live transport
here.
"""

from .adapter import BilibiliAdapter, BilibiliAdapterError, DuplicateEventError
from .client import (
    DEFAULT_BASE_URL,
    END_PATH,
    HEARTBEAT_PATH,
    HttpResponse,
    HttpTransport,
    OpenLiveClient,
    START_PATH,
    SessionError,
    SessionStateError,
    TransportError,
    WebSocketTransport,
)
from .lifecycle import (
    BackoffPolicy,
    ConnectionLifecycle,
    ConnectionLifecycleError,
    ConnectionState,
    FailureClass,
    IllegalTransitionError,
    InvalidIdentityCodeError,
)
from .openlive import (
    AuthError,
    EndRequest,
    EndResponse,
    Envelope,
    HeartbeatRequest,
    HeartbeatResponse,
    MalformedResponseError,
    OpenLiveError,
    StartRequest,
    StartResponse,
    WebSocketInfo,
    decode_auth_reply,
    encode_auth_frame,
    parse_envelope,
)
from .signing import (
    AppCredentials,
    IdentityCode,
    IdentityCodeError,
    MAX_IDENTITY_CODE_LENGTH,
    REDACTED,
    SIGNATURE_METHOD,
    SIGNATURE_VERSION,
    Secret,
    SignedRequest,
    canonical_string,
    content_md5,
    redact,
    sign_request,
)
from .wire import (
    BilibiliWireCodec,
    ControlFrame,
    FrameHeader,
    HEADER_LENGTH,
    MAX_DECOMPRESSED_LENGTH,
    MAX_NESTING_DEPTH,
    MAX_PACKET_LENGTH,
    MalformedFrameError,
    MessageEnvelope,
    Operation,
    OversizedPacketError,
    PayloadDecodeError,
    ProtocolVersion,
    TruncatedPacketError,
    UnsupportedOperationError,
    UnsupportedProtocolVersionError,
    WireError,
    decode,
    encode_frame,
    encode_heartbeat,
    encode_heartbeat_reply,
    encode_message_plain,
    encode_message_zlib,
    parse_header,
)

__all__ = [
    "AppCredentials",
    "AuthError",
    "BackoffPolicy",
    "BilibiliAdapter",
    "BilibiliAdapterError",
    "BilibiliWireCodec",
    "ConnectionLifecycle",
    "ConnectionLifecycleError",
    "ConnectionState",
    "ControlFrame",
    "DEFAULT_BASE_URL",
    "DuplicateEventError",
    "END_PATH",
    "EndRequest",
    "EndResponse",
    "Envelope",
    "FailureClass",
    "FrameHeader",
    "HEADER_LENGTH",
    "HEARTBEAT_PATH",
    "HeartbeatRequest",
    "HeartbeatResponse",
    "HttpResponse",
    "HttpTransport",
    "IdentityCode",
    "IdentityCodeError",
    "IllegalTransitionError",
    "InvalidIdentityCodeError",
    "MAX_DECOMPRESSED_LENGTH",
    "MAX_IDENTITY_CODE_LENGTH",
    "MAX_NESTING_DEPTH",
    "MAX_PACKET_LENGTH",
    "MalformedFrameError",
    "MalformedResponseError",
    "MessageEnvelope",
    "OpenLiveClient",
    "OpenLiveError",
    "Operation",
    "OversizedPacketError",
    "PayloadDecodeError",
    "ProtocolVersion",
    "REDACTED",
    "SIGNATURE_METHOD",
    "SIGNATURE_VERSION",
    "START_PATH",
    "Secret",
    "SessionError",
    "SessionStateError",
    "SignedRequest",
    "StartRequest",
    "StartResponse",
    "TransportError",
    "TruncatedPacketError",
    "UnsupportedOperationError",
    "UnsupportedProtocolVersionError",
    "WebSocketInfo",
    "WebSocketTransport",
    "WireError",
    "canonical_string",
    "content_md5",
    "decode",
    "decode_auth_reply",
    "encode_auth_frame",
    "encode_frame",
    "encode_heartbeat",
    "encode_heartbeat_reply",
    "encode_message_plain",
    "encode_message_zlib",
    "parse_envelope",
    "parse_header",
    "redact",
    "sign_request",
]
